import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

export const getServerSideProps: GetServerSideProps = async ({ res }) => {
  // The value could be undefined, so we need to use nullish coalescing
  const headerFromMiddleware = res.getHeader("From-Middleware") ?? null;

  return {
    props: {
      customHeader: headerFromMiddleware,
    },
  };
};

interface IHomeProps {
  customHeader: string | null;
}

const Home: NextPage<IHomeProps> = (props) => {
  return (
    <div className="mx-auto my-auto flex items-center justify-center h-screen flex-col space-y-5">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="font-poppins text-7xl text-green-500 font-semibold">
        Hello World!
      </h1>
      <p>{props.customHeader}</p>
    </div>
  );
};

export default Home;
